"""Update relationships with back_populates

Revision ID: 7b505cb4e648
Revises: 3b95192ab1c7
Create Date: 2024-07-23 05:38:34.277698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b505cb4e648'
down_revision = '3b95192ab1c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.alter_column('date_initiated',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)

    with op.batch_alter_table('reward', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_given', sa.Date(), nullable=False))
        
        # Specify the name of the foreign key constraint to drop
        batch_op.drop_constraint('fk_reward_item_id', type_='foreignkey')
        batch_op.drop_column('item_id')
        batch_op.drop_column('date_paid')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('reward', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_paid', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('item_id', sa.INTEGER(), nullable=False))
        
        # Recreate the foreign key constraint with the correct name
        batch_op.create_foreign_key('fk_reward_item_id', 'item', ['item_id'], ['id'])
        batch_op.drop_column('date_given')

    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.alter_column('date_initiated',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
