"""datepaid set nullable to true

Revision ID: fe8c4b25f758
Revises: 5b8192edca27
Create Date: 2024-08-01 17:28:03.863450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe8c4b25f758'
down_revision = '5b8192edca27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reward', schema=None) as batch_op:
        batch_op.alter_column('date_paid',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reward', schema=None) as batch_op:
        batch_op.alter_column('date_paid',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
